# Generated by Django 4.2.2 on 2023-06-18 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='difficulty',
            new_name='gamespec',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='genre',
            new_name='peoplenum',
        ),
        migrations.AddField(
            model_name='game',
            name='playrule',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
