# Generated by Django 4.2.2 on 2023-06-18 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_rename_title_game_title1_game_title2_game_title3'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
